export const API = {
  BASE: import.meta.env.VITE_API_URL || 'http://localhost:8080/api',

  AUTH: {
    EMPLOYEE_OTP_SEND: '/auth/employee/otp/send',
    EMPLOYEE_OTP_VERIFY: '/auth/employee/otp/verify',
    EMPLOYEE_GOOGLE: '/auth/employee/google',
    ENTERPRISE_LOGIN: '/auth/enterprise/login',
    ENTERPRISE_REGISTER: '/auth/enterprise/register',
    ADMIN_LOGIN: '/auth/admin/login',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    CHANGE_PASSWORD: '/auth/change-password',
  },

  ADMIN: {
    LOGIN: '/auth/admin/login',
    DASHBOARD: '/admin/dashboard',
    COMPANIES: '/admin/companies',
    COMPANY: (id) => `/admin/companies/${id}`,
    REVIEW: (id) => `/admin/companies/${id}/review`,
    REVIEW_DOCUMENT: (id) => `/admin/companies/${id}/documents/review`,
    COMPANY_MESSAGES: (id) => `/admin/companies/${id}/messages`,
    EMPLOYEES: '/admin/employees',
    EMPLOYEE: (id) => `/admin/employees/${id}`,
  },

  EMPLOYEE: {
    PROFILE: '/employee/profile',
    SUGGEST_COMPANIES: '/employee/suggestions/companies',
    SUGGEST_ROLES: '/employee/suggestions/roles',
    PROFILE_SETUP: '/employee/profile/setup',
    PROFILE_PHOTO: '/employee/profile/photo',
    SCORE: '/employee/score',
    VERIFICATION_STATUS: '/employee/verification/status',
    VERIFICATION_AADHAAR: '/employee/verification/aadhaar',
    VERIFICATION_BIOMETRIC: '/employee/verification/biometric',
    JOBS: '/employee/jobs',
    JOB_DOCUMENTS: (id) => `/employee/jobs/${id}/documents`,
    ACTIVITY: '/employee/activity',
    ACTIVITY_ACTION: (id) => `/employee/activity/${id}`,
    VAULT: '/employee/vault',
    SETTINGS: '/employee/settings',
    PROFESSIONAL_ID: '/employee/professional-id',
    INVITATIONS: '/employee/invitations',
    INVITATION_ACCEPT: (id) => `/employee/invitations/${id}/accept`,
    INVITATION_REJECT: (id) => `/employee/invitations/${id}/reject`,
    ACCESS_REQUESTS: '/employee/access-requests',
    ACCESS_REQUEST_APPROVE: (id) => `/employee/access-request/${id}/approve`,
    ACCESS_REQUEST_REJECT: (id) => `/employee/access-request/${id}/reject`,
    ENDORSEMENTS: '/employee/endorsements',
    ENDORSE: '/employee/endorse',
    JOB_VERIFICATION: (id) => `/employee/jobs/${id}/verification`,
    JOB_VERIFICATION_REQUEST: (id) => `/employee/jobs/${id}/verification-request`,
    VERIFICATION_REQUESTS: '/employee/verification/requests',
    VERIFICATION_CONSENT_APPROVE: (id) => `/employee/verification-requests/${id}/approve-consent`,
    VERIFICATION_CONSENT_REJECT: (id) => `/employee/verification-requests/${id}/reject-consent`,
    VERIFICATION_TAGS: '/employee/verification/tags',
    SMTP_SETTINGS: '/employee/settings/smtp',
    SMTP_TEST: '/employee/settings/smtp/test',
  },

  PUBLIC: {
    PROFILE: (slug) => `/public/profile/${encodeURIComponent(slug)}`,
    PROFILE_ACCESS: (slug) => `/public/profile/${encodeURIComponent(slug)}/request-access`,
    EMPLOYEE_INVITATION: (token) => `/public/employee-invitation/${encodeURIComponent(token)}`,
    EMPLOYMENT_VERIFICATION: (token) => `/public/employment-verification/${encodeURIComponent(token)}`,
    EMPLOYMENT_VERIFICATION_DOCUMENT: (token) =>
      `/public/employment-verification/${encodeURIComponent(token)}/document`,
    COMPANY_INVITE: (token) => `/public/company-invite/${encodeURIComponent(token)}`,
    COMPANY_INVITE_ACCEPT: (token) => `/public/company-invite/${encodeURIComponent(token)}/accept`,
    QR_JOIN: (code) => `/public/qr/${encodeURIComponent(code)}`,
    QR_JOIN_SUBMIT: (code) => `/public/qr/${encodeURIComponent(code)}/join`,
  },

  COMPANY: {
    WORKSPACE: '/company/workspace',
    TEAM: '/company/team',
    TEAM_DEPARTMENT: (department) => `/company/team/department/${encodeURIComponent(department)}`,
    INVITE_EMPLOYEE: '/company/invite-employee',
    EMPLOYEE_SEARCH: '/company/employees/search',
    INVITATIONS_PENDING: '/company/invitations/pending',
    EMPLOYEE_PROFILE: (employeeId) => `/company/employees/${employeeId}/profile`,
    EMPLOYEE_DOCUMENTS: (employeeId) => `/company/employees/${employeeId}/documents`,
    EMPLOYEE_ACCESS_STATUS: (employeeId) => `/company/employees/${employeeId}/access-status`,
    EMPLOYEE_REVOKE_ACCESS: (employeeId) => `/company/employees/${employeeId}/revoke-access`,
    ACCESS_REQUEST: '/company/access-request',
    ACCESS_REQUEST_TYPES: '/company/access-request-types',
    ACCESS_REQUESTS: '/company/access-requests',
    INSIGHTS: '/company/insights',
    PLATFORM_COMPANIES_SEARCH: '/company/platform-companies/search',
    VERIFICATION_REQUEST: '/company/verification-request',
    VERIFICATION_REQUESTS_OUTGOING: '/company/verification-requests/outgoing',
    VERIFICATION_REQUESTS_INCOMING: '/company/verification-requests/incoming',
    VERIFICATION_REQUEST_APPROVE: (id) => `/company/verification-requests/${id}/approve`,
    VERIFICATION_REQUEST_REJECT: (id) => `/company/verification-requests/${id}/reject`,
    VERIFICATION_REQUEST_COMPLETE_EMAIL: (id) => `/company/verification-requests/${id}/complete-email`,
    VERIFICATION_REQUEST_RESEND_EMAIL: (id) => `/company/verification-requests/${id}/resend-email`,
    VERIFICATION_REQUEST_REVIEW_HR: (id) => `/company/verification-requests/${id}/review-hr-response`,
    VERIFICATION_REQUEST_CONFIRM_DOCUMENT: (id) => `/company/verification-requests/${id}/confirm-document-verification`,
    EMPLOYEE_JOB_VERIFICATION_RECORD: (employeeId, jobId) =>
      `/company/employees/${employeeId}/jobs/${jobId}/verification-record`,
    EMPLOYEE_ONBOARDING: (employeeId) => `/company/employees/${employeeId}/onboarding`,
    AUDIT_LOGS: '/company/audit-logs',
    SMTP_SETTINGS: '/company/settings/smtp',
    SMTP_TEST: '/company/settings/smtp/test',
    ME_PERMISSIONS: '/company/me/permissions',
    ROLES: '/company/roles',
    ROLE: (roleId) => `/company/roles/${roleId}`,
    USERS: '/company/users',
    USER_PASSWORD: (userId) => `/company/users/${userId}/password`,
    USER_INVITE: '/company/users/invite',
    USER_INVITE_REVOKE: (inviteId) => `/company/users/invites/${inviteId}/revoke`,
    USER_ROLE: (userId) => `/company/users/${userId}/role`,
    USER_REMOVE: (userId) => `/company/users/${userId}`,
  },

  ENTERPRISE: {
    ONBOARDING: '/enterprise/onboarding',
    ONBOARDING_BASIC: '/enterprise/onboarding/basic-info',
    ONBOARDING_REGISTRATION: '/enterprise/onboarding/registration',
    ONBOARDING_DOCUMENT: (type) => `/enterprise/onboarding/documents/${type}`,
    ONBOARDING_SUBMIT: '/enterprise/onboarding/submit',
    DASHBOARD: '/enterprise/dashboard',
    WORKFORCE: '/enterprise/workforce',
    JOIN_REQUESTS: '/enterprise/join-requests',
    JOIN_REQUEST: (id) => `/enterprise/join-requests/${id}`,
    APPLICATION_STATUS: '/enterprise/application/status',
    APPLICATION_RESUBMIT: '/enterprise/application/resubmit',
    APPLICATION_MESSAGES: '/enterprise/application/messages',
    QR_ONBOARDING: '/enterprise/qr-onboarding',
    QR_ONBOARDING_ACTIVE: (id) => `/enterprise/qr-onboarding/${id}/active`,
    QR_ONBOARDING_DELETE: (id) => `/enterprise/qr-onboarding/${id}`,
  },
}

export const MEDIA_BASE = (import.meta.env.VITE_API_URL || 'http://localhost:8080/api').replace(
  /\/api\/?$/,
  '',
)
