export const API = {
  BASE: import.meta.env.VITE_API_URL || 'http://localhost:8080/api',

  AUTH: {
    EMPLOYEE_OTP_SEND: '/auth/employee/otp/send',
    EMPLOYEE_OTP_VERIFY: '/auth/employee/otp/verify',
    EMPLOYEE_GOOGLE: '/auth/employee/google',
    ENTERPRISE_LOGIN: '/auth/enterprise/login',
    ENTERPRISE_REGISTER: '/auth/enterprise/register',
    ADMIN_LOGIN: '/auth/admin/login',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
  },

  ADMIN: {
    LOGIN: '/auth/admin/login',
    DASHBOARD: '/admin/dashboard',
    COMPANIES: '/admin/companies',
    COMPANY: (id) => `/admin/companies/${id}`,
    REVIEW: (id) => `/admin/companies/${id}/review`,
  },

  EMPLOYEE: {
    PROFILE: '/employee/profile',
    PROFILE_SETUP: '/employee/profile/setup',
    PROFILE_PHOTO: '/employee/profile/photo',
    SCORE: '/employee/score',
    VERIFICATION_STATUS: '/employee/verification/status',
    VERIFICATION_AADHAAR: '/employee/verification/aadhaar',
    VERIFICATION_BIOMETRIC: '/employee/verification/biometric',
    JOBS: '/employee/jobs',
    JOB_DOCUMENTS: (id) => `/employee/jobs/${id}/documents`,
    ACTIVITY: '/employee/activity',
    ACTIVITY_ACTION: (id) => `/employee/activity/${id}`,
    VAULT: '/employee/vault',
    SETTINGS: '/employee/settings',
    PROFESSIONAL_ID: '/employee/professional-id',
    INVITATIONS: '/employee/invitations',
    INVITATION_ACCEPT: (id) => `/employee/invitations/${id}/accept`,
    INVITATION_REJECT: (id) => `/employee/invitations/${id}/reject`,
    ACCESS_REQUESTS: '/employee/access-requests',
    ACCESS_REQUEST_APPROVE: (id) => `/employee/access-request/${id}/approve`,
    ACCESS_REQUEST_REJECT: (id) => `/employee/access-request/${id}/reject`,
    ENDORSEMENTS: '/employee/endorsements',
    ENDORSE: '/employee/endorse',
  },

  PUBLIC: {
    EMPLOYEE_INVITATION: (token) => `/public/employee-invitation/${encodeURIComponent(token)}`,
    EMPLOYMENT_VERIFICATION: (token) => `/public/employment-verification/${encodeURIComponent(token)}`,
  },

  COMPANY: {
    TEAM: '/company/team',
    TEAM_DEPARTMENT: (department) => `/company/team/department/${encodeURIComponent(department)}`,
    INVITE_EMPLOYEE: '/company/invite-employee',
    INVITATIONS_PENDING: '/company/invitations/pending',
    EMPLOYEE_PROFILE: (employeeId) => `/company/employees/${employeeId}/profile`,
    EMPLOYEE_DOCUMENTS: (employeeId) => `/company/employees/${employeeId}/documents`,
    EMPLOYEE_ACCESS_STATUS: (employeeId) => `/company/employees/${employeeId}/access-status`,
    EMPLOYEE_REVOKE_ACCESS: (employeeId) => `/company/employees/${employeeId}/revoke-access`,
    ACCESS_REQUEST: '/company/access-request',
    ACCESS_REQUEST_TYPES: '/company/access-request-types',
    ACCESS_REQUESTS: '/company/access-requests',
    INSIGHTS: '/company/insights',
    VERIFICATION_REQUEST: '/company/verification-request',
    VERIFICATION_REQUESTS_OUTGOING: '/company/verification-requests/outgoing',
    VERIFICATION_REQUESTS_INCOMING: '/company/verification-requests/incoming',
    VERIFICATION_REQUEST_APPROVE: (id) => `/company/verification-requests/${id}/approve`,
    VERIFICATION_REQUEST_REJECT: (id) => `/company/verification-requests/${id}/reject`,
    VERIFICATION_REQUEST_COMPLETE_EMAIL: (id) => `/company/verification-requests/${id}/complete-email`,
    AUDIT_LOGS: '/company/audit-logs',
  },

  ENTERPRISE: {
    ONBOARDING: '/enterprise/onboarding',
    ONBOARDING_BASIC: '/enterprise/onboarding/basic-info',
    ONBOARDING_REGISTRATION: '/enterprise/onboarding/registration',
    ONBOARDING_DOCUMENT: (type) => `/enterprise/onboarding/documents/${type}`,
    ONBOARDING_SUBMIT: '/enterprise/onboarding/submit',
    DASHBOARD: '/enterprise/dashboard',
    WORKFORCE: '/enterprise/workforce',
    JOIN_REQUESTS: '/enterprise/join-requests',
    JOIN_REQUEST: (id) => `/enterprise/join-requests/${id}`,
    QR_ONBOARDING: '/enterprise/qr-onboarding',
  },
}

export const MEDIA_BASE = (import.meta.env.VITE_API_URL || 'http://localhost:8080/api').replace(
  /\/api\/?$/,
  '',
)
